### ISSUE TITLE
C# 7.0 中不支持功能“默认文本”。请使用 7.1 或更高的语言版本

### ISSUE THREAD

**Issue by kissxic** [YanZhiwei/MasterChief#2]
namespace: MasterChief.DotNet4.Utilities.Common
class:ConvertHelper
method:ToStringOrDefault

if (data != default)  default 报错 是否应改为if (data != default(DateTime)) 
CS8107  C# C# 7.0 中不支持功能“默认文本”。请使用 7.1 或更高的语言版本。

类似的问题有好几处，建议下载下来运行一次

**Comment by YanZhiwei** [comment]
嗯嗯  在vs 2019 for mac 我也发现该编译问题，稍后修复，谢谢提出～

**Comment by YanZhiwei** [comment]
已经修复了～
