### ISSUE TITLE
ApplicationHelper有使用范例么

### ISSUE THREAD

**Issue by 118119019** [YanZhiwei/MasterChief#3]
ApplicationHelper 
ApplyOnlyOneInstance
CapturedException 这几个方法怎么用，没弄懂

**Comment by YanZhiwei** [comment]
我稍后添加示例～

**Comment by YanZhiwei** [comment]
/// <summary>
        /// 应用程序的主入口点。
        /// </summary>
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            ApplicationHelper.CapturedException((ex, mode) =>
            {
                switch(mode)
                {
                    case ExceptionType.Unhandled:
                        MessageBox.Show("发生未捕获的异常:" + ex.Message);
                        break;

                    case ExceptionType.Thread:
                        MessageBox.Show("发生线程异常:" + ex.Message);
                        break;
                }
            });
            ApplicationHelper.ApplyOnlyOneInstance(t =>
            {
                if(t)
                {
                    FormHelper.ShowLoginForm<FormLogin, FormMain>();
                }
                //Application.Run(new winMain());
                else
                {
                    MessageBox.Show("已经有程序在运行。");
                }
            });
        }
-----------------------------------------------------------------------------------------------------------
        private void Form1_Load(object sender, EventArgs e)
        {
            ApplicationHelper.CapturedExit<FormMain>(this, () =>
            {
                if (MessageBox.Show("确认退出？", "提示", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    return true;

                return false;
            });
        }
